
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Barang/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>


<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Barang<small>List All</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Barang</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- <div class="col-sm-8"> -->
                  <div class="col-md-4">
                        <?php
                                        // Open form and set URL for submit form
                        echo form_open('administrator/barang/add_search');

                        // Show Name Field in View Page
                        // echo form_label('Kode Inventaris', 'kode_inventaris');
                        $data= array(
                        'name' => 'kode_inventaris',
                        'class'   => 'form-horizontal', 
                        'placeholder' => 'Search Kode Inventaris',
                        'class' => 'form-control'
                        );
                        echo form_input($data);


                        ?>
                </div>
                <div class="col-md-2">
                      <div id="form_button">
                      <?php
                      $data = array(
                      'type' => 'submit',
                      'value'=> 'Search',
                      'class'=> 'submit'
                      );
                      echo form_submit($data); ?>
                      </div>

                      <?php echo form_close();?>               
                                   
                </div>
                <div class="col-md-4">                               
                               
                        <?php
                                        // Open form and set URL for submit form
                        echo form_open('administrator/barang/add_search_namabrg');

                        // Show Name Field in View Page
                        // echo form_label('Nama Barang', 'nama_barang');
                        $data= array(
                        'name' => 'nama_barang',
                        'class'   => 'form-horizontal', 
                        'placeholder' => 'Search Nama Barang',
                        'class' => 'form-control'
                        );
                        echo form_input($data);


                        ?>
                </div>
                <div class="col-md-2">                               
                   
                        <div id="form_button">
                        <?php
                        $data = array(
                        'type' => 'submit',
                        'value'=> 'Search',
                        'class'=> 'submit'
                        );
                        echo form_submit($data); ?>
                        </div>

                        <?php echo form_close();?>               
                </div>                   
                                    
        </div>
                               
                               
                         
                    
                    <!-- </div> -->
                  <!-- </div> -->
                </div>
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('barang_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="add new Barang (Ctrl+a)" href="<?=  site_url('administrator/barang/add'); ?>"><i class="fa fa-plus-square-o" ></i> Add New Barang</a>
                        <?php }) ?>
                        <?php is_allowed('barang_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export Barang" href="<?= site_url('administrator/barang/export'); ?>"><i class="fa fa-file-excel-o" ></i> Export XLS</a>
                        <?php }) ?>
                        <?php is_allowed('barang_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export pdf Barang" href="<?= site_url('administrator/barang/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> Export PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Barang</h3>
                     <h5 class="widget-user-desc">List All Barang <i class="label bg-yellow"><?= $barang_counts; ?>  items</i></h5>
                  </div>
                 
                  <form name="form_barang" id="form_barang" action="<?= base_url('administrator/barang/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Kode Barang</th>
                           <th>Nama Barang</th>
                           <th>Kode Inventaris</th>
                           <th>Barcode</th>
                           <th>Merek</th>
                           <th>Kategori</th>
                           <th>Kondisi</th>
                           <th>Jumlah</th>
                           <th>Satuan</th>
                           <th>Gambar</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_barang">
                     <?php foreach($barangs as $barang): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $barang->id_barang; ?>">
                           </td>
                           
                           <td><?= _ent($barang->kode_barang); ?></td> 
                           <td><?= _ent($barang->nama_barang); ?></td> 
                           <td><?= _ent($barang->kode_inventaris); ?></td> 
                           <td><?php if (!empty($barang->kode_inventaris))
                           {
?>
                            
                            
            
              
                  <center><img src="<?= BASE_ASSET; ?>/php-barcode-master/barcode.php?text=<?php  echo $barang->kode_inventaris; ?>&print=true&size=45" /> </center>
               
           
                           <!--<center> <img style="padding-top: 5px;" src="<?= BASE_ASSET; ?>/barcode/barcode.php?codetype=Code39&size=40&text=<?php echo $barang->kode_inventaris?>&print=true"/></center>-->
<?php 
                          }
?>

                          </td> 
                           <td><?= _ent($barang->merek); ?></td> 
                           <td><?= _ent($barang->kategori); ?></td> 
                           <td><?= _ent($barang->kondisi); ?></td> 
                           <td><?= _ent($barang->jumlah); ?></td> 
                           <td><?= _ent($barang->satuan); ?></td> 
                           <td>
                              <?php if (!empty($barang->gambar)): ?>
                                <?php if (is_image($barang->gambar)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/barang/' . $barang->gambar; ?>">
                                  <img src="<?= BASE_URL . 'uploads/barang/' . $barang->gambar; ?>" class="image-responsive" alt="image barang" title="gambar barang" width="40px">
                                </a>
                                <?php else: ?>
                                  <a href="<?= BASE_URL . 'administrator/file/download/barang/' . $barang->gambar; ?>">
                                   <img src="<?= get_icon_file($barang->gambar); ?>" class="image-responsive image-icon" alt="image barang" title="gambar <?= $barang->gambar; ?>" width="40px"> 
                                 </a>
                                <?php endif; ?>
                              <?php endif; ?>
                           </td>
                            
                           <td width="200">
                             

                              <?php is_allowed('barang_view', function($b) use ($barang){?>
                              <a href="<?= site_url('administrator/barang/view/' . $barang->id_barang); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> View
                              <?php }) ?>
                              <?php is_allowed('barang_update', function($b) use ($barang){?>
                              <a href="<?= site_url('administrator/barang/edit/' . $barang->id_barang); ?>" class="label-default"><i class="fa fa-edit "></i> Update</a>
                              <?php }) ?>
                              <?php is_allowed('barang_delete', function($b) use ($barang){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/barang/delete/' . $barang->id_barang); ?>" class="label-default remove-data"><i class="fa fa-close"></i> Remove</a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($barang_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Barang data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="apply bulk actions">Apply</button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="Filter" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value="">All</option>
                            <option <?= $this->input->get('f') == 'nama_barang' ? 'selected' :''; ?> value="nama_barang">Nama Barang</option>
                           <option <?= $this->input->get('f') == 'merek' ? 'selected' :''; ?> value="merek">Merek</option>
                           <option <?= $this->input->get('f') == 'kategori' ? 'selected' :''; ?> value="kategori">Kategori</option>
                           <option <?= $this->input->get('f') == 'kondisi' ? 'selected' :''; ?> value="kondisi">Kondisi</option>
                           <option <?= $this->input->get('f') == 'jumlah' ? 'selected' :''; ?> value="jumlah">Jumlah</option>
                           <option <?= $this->input->get('f') == 'satuan' ? 'selected' :''; ?> value="satuan">Satuan</option>
                           <option <?= $this->input->get('f') == 'gambar' ? 'selected' :''; ?> value="gambar">Gambar</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="filter search">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/barang');?>" title="reset filters">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Are you sure?",
          text: "data to be deleted can not be restored!",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes, delete it!",
          cancelButtonText: "No, cancel plx!",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_barang').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "Are you sure?",
            text: "data to be deleted can not be restored!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/barang/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "Please choose bulk action first!",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>